name: Repository dispatch (multi)

on:
  release:
    types: [published]
  workflow_dispatch:
  push: # remove this

jobs:
  repo_dispatch:
    runs-on: ubuntu-latest
    env:
      ORG: carolinebridge-oicr
    strategy:
      matrix:
        repo:
          - 'carolinebridge-oicr/test-repo-b'
          - 'carolinebridge-oicr/test-repo-c'
          - 'carolinebridge-oicr/jbrowse-react-linear-genome-view-nextjs-demo'

    steps:
      - name: Dispatch jbrowse-components release event to dependent GMOD repositories
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: ${{ matrix.repo }}
          event-type: auto_publish
          client-payload: '{"ref": "${{github.ref}}", "version": "${{ github.event.inputs.version }}"}'
