name: Repository dispatch

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  repo_dispatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: repository dispatch jbrowse_components
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}
        EVENT: auto_publish
        ORG: carolinebridge-oicr
        REPO: test-repo-b
      run: |
        curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
